apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: hostpath.csi.k8s.io-b
kind: VolumeSnapshotClass
metadata:
  annotations:
    meta.helm.sh/release-name: csi-hostpath-b
    meta.helm.sh/release-namespace: csi-hostpath-b
  labels:
    app.kubernetes.io/managed-by: Helm
  name: csi-hostpath-b