apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    kubesphere.io/alias-name: local-storage
{{- if .Values.storageClass.isDefaultStorageClass }}
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: {{ .Values.driver.name }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
