# Usage of the v1 API implies that the cluster must have
# external-snapshotter v4.x installed.
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
{{- if .Values.snapshotClass.isDefaultSnapshotClass }}
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
{{- end }}
  name: {{ .Values.snapshotClass.name }}
driver: {{ .Values.driver.name }}
deletionPolicy: Delete
